services:
  - type: web
    name: caption-crow-server
    env: docker
    plan: free
    region: singapore
    healthCheckPath: /api/healthz

    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_APP_PASSWORD
        sync: false
